---
site_name: Clak
site_description: A Python argparse library with classes
repo_url: https://github.com/mrjk/python-clak
repo_name: mrjk/python-clak

docs_dir: content/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tabs
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  # - literate-nav:
  #     nav_file: SUMMARY.md

  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      auto_title: false
      linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # auto_append: ["../LICENSE"]
      base_path: [".."]
      auto_append:
        - includes/abbreviations.md


  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - sane_lists

  # Ensure we have easy list parsing
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_source: true
            show_root_heading: true

nav:
  - Home:
      - Index: index.md
      - Install: install.md
      - Quickstart: quickstart.md
  - Guides:
      - Basic application: guides/guide_101.md
      - Nested application: guides/guide_102.md
      - Best Practices: guides/best_practices.md
  - Documentation:
      - Features: docs/features.md
      - Execution: docs/execution.md
      # - Fields: docs/fields.md
      # - Loaders: docs/loaders.md
      # - Cast: docs/cast.md

  - Reference:
      - Overview:

          - Module: reference/module.md

          # - Diagram: reference/diagram.md
          - Architecture: architecture/list.md

      - Core:
          - Parser: reference/parser.md
          - Nodes: reference/nodes.md
      - Plugins:
          - Completion: reference/plugin_complete.md
          - Logging: reference/plugin_logging.md
          - Config: reference/plugin_config.md
          # - Plugins:

  - Project:
      - Contributing: project/CONTRIBUTING.md
      - Code of Conduct: project/CODE_OF_CONDUCT.md
      - License: project/license.md
