---
site_name: Clak
site_description: A Python argparse library with classes
repo_url: https://github.com/mrjk/python-clak
repo_name: mrjk/python-clak

docs_dir: content/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - navigation.tabs

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  # - literate-nav:
  #     nav_file: SUMMARY.md
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # auto_append: ["../LICENSE"]
      base_path: [".."]

  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - sane_lists

  # Ensure we have easy list parsing
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: True

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [..]
          options:
            show_source: true
            show_root_heading: true

nav:
  - Home: 
      - Index: index.md
      - Install: install.md
      - Quickstart: quickstart.md
  - Guides:
      - Basic Guide: guides/guide_101.md
      - Nested Configuration: guides/guide_102_nested.md
      - Feeding Values: guides/guide_103_feeding_values.md
      - Best Practices: guides/best_practices.md
  - Documentation:
      - Configurations: docs/configurations.md
      - Fields: docs/fields.md
      - Loaders: docs/loaders.md
      - Cast: docs/cast.md

  - Reference:
      - Overview:

        - API: reference/api.md
        - Plugins: reference/plugins.md

        # - Diagram: reference/diagram.md
        - Architecture: architecture/list.md
      - Plugins:
        - Completion: reference/plugin_complete.md
        - Logging: reference/plugin_logging.md
        - Config: reference/plugin_config.md
      # - Plugins:

  - Project:
    - Contributing: info/contributing.md
    - Code of Conduct: info/code_of_conduct.md
    - License: info/license.md
